[package]
name = "ziggurat"
version = "0.1.0"
authors = ["Niklas Long <niklas@equilibrium.co>, Mirko von Leipzig <mirko@equilibrium.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_matches = "1.5"
async-trait = "0.1.53"
bytes = "1"
hex = "0.4.3"
histogram = "0.6.9"
home = "0.5.3"
lazy_static = "1.4.0"
metrics = "0.18"
metrics-util = "0.12"
ordered-float = "2.10"
parking_lot = "0.12"
pea2pea = "0.35"
rand = "0.8"
rand_chacha = "0.3"
sha2 = "0.10"
tabled = "0.6"
time = "0.3"
toml = "0.5.8"

[dependencies.futures-util]
version = "0.3"
features = [ "sink" ]

[dependencies.serde]
version = "1"
features = [ "derive" ]

[dependencies.tokio]
version = "1"
features = [ "full" ]

[dependencies.tokio-util]
version = "0.7"
features = [ "codec" ]

[dependencies.tracing]
version = "0.1"
default-features = false

[dependencies.tracing-subscriber]
version = "0.3"
features = [ "env-filter", "fmt" ]

